BEGIN TRANSACTION;
CREATE TABLE Pet (PET_ID INTEGER PRIMARY KEY, TYPE_ID NUMERIC, NAME TEXT, CREATION NUMERIC, HEALTH NUMERIC);
CREATE TABLE Type (TYPE_ID INTEGER PRIMARY KEY, Qml TEXT);
INSERT INTO Type VALUES(1,'Pet1.qml');
INSERT INTO Type VALUES(2,'Pet2.qml');
COMMIT;
